#[repr(u32)]
#[derive(Copy, Clone)]
pub enum ColorRepr {
    RED = gl::RED,
    RG = gl::RG,
    RGB = gl::RGB,
    BGR = gl::BGR,
    RGBA = gl::RGBA,
    BGRA = gl::BGRA,
    RedInteger = gl::RED_INTEGER,
    RgInteger = gl::RG_INTEGER,
    RgbInteger = gl::RGB_INTEGER,
    BgrInteger = gl::BGR_INTEGER,
    RgbaInteger = gl::RGBA_INTEGER,
    BgraInteger = gl::BGRA_INTEGER,
    StencilIndex = gl::STENCIL_INDEX,
    DepthComponent = gl::DEPTH_COMPONENT,
    DepthStencil = gl::DEPTH_STENCIL,
}

#[allow(non_camel_case_types)]
#[repr(u32)]
#[derive(Copy, Clone)]
pub enum ColorInternal {
    RGBA32F = gl::RGBA32F,
    RGBA16F = gl::RGBA16F,
    RG32F = gl::RG32F,
    RG16F = gl::RG16F,
    R11F_G11F_B10F = gl::R11F_G11F_B10F,
    R32F = gl::R32F,
    R16F = gl::R16F,
    RGBA32UI = gl::RGBA32UI,
    RGBA16UI = gl::RGBA16UI,
    RGB10_A2UI = gl::RGB10_A2UI,
    RGBA8UI = gl::RGBA8UI,
    RG32UI = gl::RG32UI,
    RG16UI = gl::RG16UI,
    RG8UI = gl::RG8UI,
    R32UI = gl::R32UI,
    R16UI = gl::R16UI,
    R8UI = gl::R8UI,
    RGBA32I = gl::RGBA32I,
    RGBA16I = gl::RGBA16I,
    RGBA8I = gl::RGBA8I,
    RG32I = gl::RG32I,
    RG16I = gl::RG16I,
    RG8I = gl::RG8I,
    R32I = gl::R32I,
    R16I = gl::R16I,
    R8I = gl::R8I,
    RGBA16 = gl::RGBA16,
    RGB10_A2 = gl::RGB10_A2,
    RGBA8 = gl::RGBA8,
    RG16 = gl::RG16,
    RG8 = gl::RG8,
    R16 = gl::R16,
    R8 = gl::R8,
    RGBA16_SNORM = gl::RGBA16_SNORM,
    RGBA8_SNORM = gl::RGBA8_SNORM,
    RG16_SNORM = gl::RG16_SNORM,
    RG8_SNORM = gl::RG8_SNORM,
    R16_SNORM = gl::R16_SNORM,
    R8_SNORM = gl::R8_SNORM,
}